---
- name: Check {{ service_name }} on managed nodes
  hosts: '*'
  become: false
  vars: 
    service_name: swiagentd.service

  tasks:
    - name: Check if {{ service_name}} is active
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
      register: service_status
      ignore_errors: true

    - name: Display {{ service_name }} status
      ansible.builtin.debug:
        msg: >
          Service '{{ service_name }}' on {{ inventory_hostname }} is 
          {% if service_status is failed %} 
            NOT running or does not exist.
          {% else %} 
            running.
          {% endif %}
